services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: file
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
  nodejs:
    container_name: nodeappcontainer
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeapp:v2
    volumes:
      - .:HOME/nodeapp:/code
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'root'
      DB_PASSWORD: 'letmein'
      DB_NAME: file
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 5000
    depends_on:
      - mysqldb
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge