CREATE DATABASE IF NOT EXISTS patientsdb;

USE patientsdb;

CREATE TABLE IF NOT EXISTS `file` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `fileName` VARCHAR(255) NOT NULL,
  `fileSize` INT NOT NULL,
  `uploadedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

